version: 0.2

env:
  variables:
    s3_output: "uocwebrisupport"
    hugo_version: "0.49"

phases:
  install:
    runtime-versions:
      golang: 1.12
    commands:
      - wget "https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_${hugo_version}_Linux-64bit.deb"
      - dpkg -i hugo_${hugo_version}_Linux-64bit.deb
    finally:
      - hugo version
  build:
    commands:
      - hugo
      - cd public
      - aws cloudsearchdomain upload-documents --endpoint-url http://oc-webri-2dz3yckt2f5cjq7hcsbois6nw4.eu-west-1.cloudsearch.amazonaws.com --content-type application/json --documents .
      - aws s3 sync . s3://${s3_output} --delete --acl public-read
    finally:
      - echo "Script finished running"