version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
      - dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
    finally:
      - hugo version
  pre_build:
    commands:
      - node ./bin/rename-languages.js
    finally:
      - echo "Finished renaming language files"
  build:
    commands:
      - hugo
      - cd public/ && aws s3 sync index.html s3://${BUCKET_S3}/ri_live/index.html --acl public-read
      - cd ./ca && aws s3 sync . s3://${BUCKET_S3}/ri_live/ca --acl public-read
      - cd ../es && aws s3 sync . s3://${BUCKET_S3}/ri_live/es --acl public-read
      - cd ../en && aws s3 sync . s3://${BUCKET_S3}/ri_live/en --acl public-read
      - cd ../img && aws s3 sync . s3://${BUCKET_S3}/ri_live/img --acl public-read
      - cd ../js && aws s3 sync . s3://${BUCKET_S3}/ri_live/js --acl public-read
      - cd ../css && aws s3 sync . s3://${BUCKET_S3}/ri_live/css --acl public-read
      - cd .. && aws cloudsearchdomain --endpoint-url ${CLOUDSEARCH_URL} upload-documents --content-type application/json --documents ./ca/index.json
    finally:
      - echo "Script finished running"