org: jccarhuas
app: webri
service: webri-cloudsearch

provider:
  name: aws
  runtime: python3.6
  region: $AWS_DEFAULT_REGION
  stage: ${opt:stage, self:custom.defaultStage}
   
resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
functions:
  test:
    handler: event.test
    events:
      - http:
          path: user/create
          method: get
          cors: true
  search:
    handler: event.search
    events:
      - http:
          path: user/search
          method: get
          cors: true
custom:
  defaultStage: dev
