org: uoc
app: webri
service: webri-cloudsearch

provider:
  name: aws
  runtime: python3.6
  region: ${opt:region, self:custom.defaultRegion}
  stage: ${opt:stage, self:custom.defaultStage}
   
resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
functions:
  search:
    handler: event.search
    events:
      - http:
          path: api-ri/search
          method: get
          cors: true
custom:
  defaultStage: dev
  defaultRegion: eu-west-1
